INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(1,'Jec','Rodomil','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(2,'Gawlek','Libert ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(3,'Szwedt','Osiegniew','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(4,'Ilinski','Wiola','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(5,'Perdela','Hubys�awa ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(6,'Nokier','Stanislawa','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(7,'Swiec','Ciecimiar ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(8,'Sudan','Adela','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(9,'Ilcew','Wiktor','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(10,'Skurupka','Nadar ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(11,'Mordyk','Namys�aw ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(12,'Stesiak','Ludomi�a ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(13,'Brotek','Izka','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(14,'Kocizewski','Maksym ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(15,'Rewuski','Falimir','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(16,'Peta','Mi�obor ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(17,'Nesterczyk','Leonid ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(18,'Tumanis','Drogomys� ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(19,'Baczunk','Czas�aw ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(20,'Stamski','Dalibor ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(21,'Josinek','Dobrociech ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(22,'Miletic','Wiwianna','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(23,'Orgasinski','Bogna','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(24,'Pakulnicewicz','Gienek','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(25,'Garbat','Erwina ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(26,'Oczkos','Eligiusz ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(27,'Klinkorz','Dobrowit ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(28,'Bielunkiewicz','Laura ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(29,'Helmik','Maja ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(30,'Rehing','Maryla ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(31,'Gersiak','Krzysztof ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(32,'Kukulo','Fortunat ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(33,'Fedym','Niedamir ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(34,'Ligendza','Izyda ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(35,'Zybluk','Falibog','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(36,'Dutsek','Teresa','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(37,'Prezyna','Humbelina ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(38,'Bode','Hiacynt ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(39,'Rikiel','Cieszymys� ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(40,'Gembarski','Manswet ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(41,'Hasenauer','Kamil ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(42,'Bruchowiecka','Nawoj ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(43,'Gebiec','Lech','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(44,'Gardyjan','Antek','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(45,'Michaski','Gajusz','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(46,'Jaskulecki','Romek','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(47,'Smutrykowski','Przemek','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(48,'Natulka','Dagmara ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(49,'Korsieko','Naum ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(50,'Narostka','Krzes�aw ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(51,'Patorczyk','Estera ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(52,'Synowiec','Jarostryj ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(53,'Smiercioch','J�zefina ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(54,'Rajszel','Teodor','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(55,'Kaszuda','Domas�awa ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(56,'Szwerubowicz','Mi�osz ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(57,'Kupferstein','Staslaw','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(58,'Obalewicz','Ula','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(59,'Howor','Tyberiusz','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(60,'Budynkiewicz','Cyriak ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(61,'Wesolly','Augustyna','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(62,'Gugolska','Liliana','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(63,'Rorczak','Karol ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(64,'Jaslak','Kaja ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(65,'Krening','Fabrycy','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(66,'Suliga','Artek','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(67,'Dudzicki','Hortensja ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(68,'Bajszczak','Krystian ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(69,'Littawer','Eustacjusz ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(70,'Bangiert','Cies�aw ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(71,'Rosielewski','Joachima ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(72,'Kalaczuk','Niestoj ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(73,'Koceda','Wirginia','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(74,'Miezaniec','Stefania','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(75,'Sztiglic','Bartosz','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(76,'Stick','Patrycjusz','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(77,'Wernoch','Nastazja ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(78,'Masnik','Nicefor ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(79,'Farbiasz','Napoleon ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(80,'Rysiel','Barnim','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(81,'Riclik','Domos�aw ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(82,'Gawreliuk','Dromi� ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(83,'Graben','Witold','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(84,'Kucejewski','Elka','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(85,'Chynasinski','Melania ','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(86,'Chlona','Alberta','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(87,'Antkowicz','Barbara','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(88,'Edler','Bernardyna','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(89,'Bakerak','Rudolfina','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(90,'Betlej','Mironiega ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(91,'Kopciszewska','Darek','prof');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(92,'Gilewski','Felicja ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(93,'Dwonkowski','Kordula ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(94,'Biller','Felicjan ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(95,'Bedyniak','Florenty ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(96,'Grogol','Olga','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(97,'Habola','Gotfryd ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(98,'Falbinski','Liwiusz ','dr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(99,'Jamdula','Eustachy ','mgr');
INSERT INTO g1_wykladowca(nr_wykl,nazwisko,imie,stopien) VALUES(100,'Polchlopien','Lidka','dr');
